### ISSUE TITLE
CSS Font Imports

### ISSUE THREAD

**Issue by MoparWeb** [rob204/Web-Cleaner-Chrome-Extension#3]
I've noticed within the past day or two that the @import of fonts within the progress page are not doing such and reverting to Calibri, etc. Adding 'Source Code Pro' to the newly added ".reportHolder select" fails also.

@import url(https://fonts.googleapis.com/css?family=Source+Code+Pro);

**Comment by rob204** [comment]
Good catch. **@import** must precede all of our other rules to work. 

see: https://developer.mozilla.org/en-US/docs/Web/CSS/@import
