### ISSUE TITLE
Can't enter a LF/CR in the four text areas on the options page in Vivaldi

### ISSUE THREAD

**Issue by akgay** [rob204/Web-Cleaner-Chrome-Extension#5]
If you try to add a line to the list in any of the textarea lists on the Options page, you are unable to do so.  Inspector reports the following error:
Uncaught TypeError: Cannot read property 'blur' of null
    at HTMLDocument.Pikaday.self._onKeyChange (pikaday.js:489)

**Comment by rob204** [comment]
Thank you. Didn't notice the enter key stopped working. I've disabled the stepsForm package for the time being.
